### ISSUE TITLE
encode error with famous Tiktok Apk.

### ISSUE THREAD

**Issue by xxxman2008** [shroudedcode/apk-mitm#31] opened 2021-01-07 19:29 UTC
i'm using "npx apk-mitm" commond . and installed apk-mitm from npm. it should be the latest release ,i think.

I try to use apk-mitm to repack Tiktok Apk . but failed.

Test machine:
Ubuntu server 18.04
JAVA:
   openjdk version "1.8.0_275"
  OpenJDK Runtime Environment (build 1.8.0_275-8u275-b01-0ubuntu1~18.04-b01)
  OpenJDK 64-Bit Server VM (build 25.275-b01, mixed mode)
Nodejs:
  v10.23.0 with npm 6.14.8

I attached the logs  and the apk ( please change the extension name) for your reference .

Thank you in advance .

[logs.zip](https://github.com/shroudedcode/apk-mitm/files/5783515/logs.zip)

[aweme_douyin-huidu-gw-control-1014_v1015_140101_176a_1608723172.zip](https://github.com/shroudedcode/apk-mitm/files/5783557/aweme_douyin-huidu-gw-control-1014_v1015_140101_176a_1608723172.zip)
[aweme_douyin-huidu-gw-control-1014_v1015_140101_176a_1608723172.z01.zip](https://github.com/shroudedcode/apk-mitm/files/5783546/aweme_douyin-huidu-gw-control-1014_v1015_140101_176a_1608723172.z01.zip)
[aweme_douyin-huidu-gw-control-1014_v1015_140101_176a_1608723172.z02.zip](https://github.com/shroudedcode/apk-mitm/files/5783547/aweme_douyin-huidu-gw-control-1014_v1015_140101_176a_1608723172.z02.zip)
[aweme_douyin-huidu-gw-control-1014_v1015_140101_176a_1608723172.z03.zip](https://github.com/shroudedcode/apk-mitm/files/5783548/aweme_douyin-huidu-gw-control-1014_v1015_140101_176a_1608723172.z03.zip)
[aweme_douyin-huidu-gw-control-1014_v1015_140101_176a_1608723172.z04.zip](https://github.com/shroudedcode/apk-mitm/files/5783549/aweme_douyin-huidu-gw-control-1014_v1015_140101_176a_1608723172.z04.zip)
[aweme_douyin-huidu-gw-control-1014_v1015_140101_176a_1608723172.z05.zip](https://github.com/shroudedcode/apk-mitm/files/5783551/aweme_douyin-huidu-gw-control-1014_v1015_140101_176a_1608723172.z05.zip)
[aweme_douyin-huidu-gw-control-1014_v1015_140101_176a_1608723172.z06.zip](https://github.com/shroudedcode/apk-mitm/files/5783552/aweme_douyin-huidu-gw-control-1014_v1015_140101_176a_1608723172.z06.zip)t
[aweme_douyin-huidu-gw-control-1014_v1015_140101_176a_1608723172.z07.zip](https://github.com/shroudedcode/apk-mitm/files/5783554/aweme_douyin-huidu-gw-control-1014_v1015_140101_176a_1608723172.z07.zip)
[aweme_douyin-huidu-gw-control-1014_v1015_140101_176a_1608723172.z08.zip](https://github.com/shroudedcode/apk-mitm/files/5783555/aweme_douyin-huidu-gw-control-1014_v1015_140101_176a_1608723172.z08.zip)
[aweme_douyin-huidu-gw-control-1014_v1015_140101_176a_1608723172.z09.zip](https://github.com/shroudedcode/apk-mitm/files/5783556/aweme_douyin-huidu-gw-control-1014_v1015_140101_176a_1608723172.z09.zip)

**Comment by shroudedcode** [comment] 2021-01-07 22:10
This seems to be a duplicate of #14. As I said [there](https://github.com/shroudedcode/apk-mitm/issues/14#issuecomment-611081886), this is an issue with Apktool that can't be fixed in `apk-mitm`. Please go through the error messages in `encoding-aapt.failed.log` and `encoding-aapt2.failed.log` and see if you can find relevant issues to upvote on [the Apktool issue tracker](https://github.com/iBotPeaches/Apktool/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc). [This one](https://github.com/iBotPeaches/Apktool/issues/1927) is definitely related.

**Closed by shroudedcode** 2021-01-07 22:10 UTC
