### ISSUE TITLE
(.xapk/.apks) does not extract "loop"

### ISSUE THREAD

**Issue by Titoot** [shroudedcode/apk-mitm#66] opened 2021-09-08 07:59 UTC
as you can see it keeps on looping when i provide it with xapk or an apks file
also I checked the temp folder and it's empty
my apk:
https://apkpure.com/mr-ahmed-samir/com.sha3booony.dev.mrahmedsamir/
```
H:\platform-tools>apk-mitm "Mr Ahmed Samir_v1.4.13_apkpure.com.xapk"

  ╭ apk-mitm v1.1.0
  ├ apktool v2.6.0
  ╰ uber-apk-signer v1.2.1

  Using temporary directory:
  C:\Users\Titoot\AppData\Local\Temp\apk-mitm-9464448e0b4def147b7cb56ce0cf9435

  / Extracting APKs
    Finding base APK path
    Patching base APK
    Signing APKs
    Compressing APKs
```

**Comment by shroudedcode** [comment] 2021-09-24 13:40
`apk-mitm` getting stuck on certain steps without any logs or errors [seems to be a common issue under Windows](https://github.com/shroudedcode/apk-mitm/issues/9) which is very difficult to investigate as there's not a single clue to go off of. My suggestion would be to try patching the app again on a system running Linux or macOS (a virtual machine is enough).

**Comment by shroudedcode** [comment] 2021-10-30 16:00
Closing this as there isn't any way for me to reproduce this at the moment.

**Closed by shroudedcode** 2021-10-30 16:00 UTC
Labels: windows
