### ISSUE TITLE
brut.directory.DirectoryException: Error copying file: ?	 .xml

### ISSUE THREAD

**Issue by s3xL0rd** [shroudedcode/apk-mitm#28] opened 2020-12-17 18:54 UTC
Hi, 
First of all thanks for the work done, I have the following problem, could you please tell me what it could be?
I copy this from the directory (The full logs of all commands are available here)

```
I: Using Apktool 2.5.0 on com.someone.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: C:\Users\Username~1\AppData\Local\Temp\apk-mitm-bfe4ff5a1e08401512e8dbdf0609e3cf\framework\1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Copying assets and libs...
I: Copying unknown files...
Exception in thread "main" brut.androlib.AndrolibException: brut.directory.DirectoryException: Error copying file: ?	 .xml
	at brut.androlib.Androlib.decodeUnknownFiles(Androlib.java:216)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:180)
	at brut.apktool.Main.cmdDecode(Main.java:179)
	at brut.apktool.Main.main(Main.java:82)
Caused by: brut.directory.DirectoryException: Error copying file: ?	 .xml
	at brut.directory.DirUtil.copyToDir(DirUtil.java:91)
	at brut.directory.AbstractDirectory.copyToDir(AbstractDirectory.java:208)
	at brut.androlib.Androlib.decodeUnknownFiles(Androlib.java:209)
	... 3 more
Caused by: java.io.IOException: The filename, directory name, or volume label syntax is incorrect 
	at java.io.WinNTFileSystem.canonicalize0(Native Method)
	at java.io.WinNTFileSystem.canonicalize(Unknown Source)
	at java.io.File.getCanonicalPath(Unknown Source)
	at brut.util.BrutIO.sanitizeUnknownFile(BrutIO.java:90)
	at brut.directory.DirUtil.copyToDir(DirUtil.java:84)
	... 5 more
```

**Comment by shroudedcode** [comment] 2020-12-18 09:06
This issue is caused by Apktool (which `apk-mitm` is based on). It's a [known issue](https://github.com/iBotPeaches/Apktool/issues/1460#issuecomment-289436058) and it only seems to appear on Windows (due to restrictions Windows imposes on file names). Your only chance at the moment is to try patching the APK again on Linux or macOS. If you don't have a computer running either of those systems handy, you can always set up a Linux virtual machine (any popular distribution, for example Ubuntu, should work) or try [using the "Windows Subsystem for Linux"](https://docs.microsoft.com/en-us/learn/modules/get-started-with-windows-subsystem-for-linux/).

**Comment by shroudedcode** [comment] 2020-12-29 22:45
Closing this because there's no way to avoid this problem apart from not using Windows.

**Closed by shroudedcode** 2020-12-29 22:45 UTC
Labels: apktool, windows
