### ISSUE TITLE
invalid resource directory name /.../res navigation

### ISSUE THREAD

**Issue by dgbkn** [shroudedcode/apk-mitm#62] opened 2021-08-24 08:19 UTC
```
  ╭ apk-mitm v1.0.3
  ├ apktool v2.5.0
  ╰ uber-apk-signer v1.2.1

  Using temporary directory:
  C:\Users\anand\AppData\Local\Temp\apk-mitm-e76e6dcdade8796291f9bc74bf73b3ff

  √ Checking prerequisities
  √ Decoding APK file
  √ Applying patches
  > Encoding patched APK file
    ↓ Encoding using AAPT2 [skipped]
      → Failed, falling back to AAPT...
    × Encoding using AAPT [fallback]
      → I: Building resources...
    Signing patched APK file

   Failed!  An error occurred:

I: Using Apktool 2.5.0
I: Checking whether sources has changed...
I: Checking whether sources has changed...
I: Checking whether sources has changed...
I: Checking whether sources has changed...
I: Checking whether sources has changed...
I: Checking whether resources has changed...
I: Building resources...
W: invalid resource directory name: C:\Users\anand\AppData\Local\Temp\apk-mitm-e76e6dcdade8796291f9bc74bf73b3ff\decode\res navigation
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\anand\AppData\Local\Temp\brut_util_Jar_14916821644510918370659886449005326021.tmp, p, --forced-package-id, 127, --min-sdk-version, 21, --target-sdk-version, 27, --version-code, 203230094, --version-name, 32.92708094.0, --no-version-vectors, -F, C:\Users\anand\AppData\Local\Temp\APKTOOL17995142851897372804.tmp, -e, C:\Users\anand\AppData\Local\Temp\APKTOOL10730232835471508005.tmp, -0, arsc, -I, C:\Users\anand\AppData\Local\Temp\apk-mitm-e76e6dcdade8796291f9bc74bf73b3ff\framework\1.apk, -S, C:\Users\anand\AppData\Local\Temp\apk-mitm-e76e6dcdade8796291f9bc74bf73b3ff\decode\res, -M, C:\Users\anand\AppData\Local\Temp\apk-mitm-e76e6dcdade8796291f9bc74bf73b3ff\decode\AndroidManifest.xml]

  The full logs of all commands are available here:
  C:\Users\anand\AppData\Local\Temp\apk-mitm-e76e6dcdade8796291f9bc74bf73b3ff\logs

```

![image](https://user-images.githubusercontent.com/65810521/130582375-1c21d362-abb8-421b-a839-ebf785e17bda.png)

FULL LOGS
[encoding-aapt.failed.log](https://github.com/shroudedcode/apk-mitm/files/7037641/encoding-aapt.failed.log)
[encoding-aapt2.failed.log](https://github.com/shroudedcode/apk-mitm/files/7037642/encoding-aapt2.failed.log)
[decoding.log](https://github.com/shroudedcode/apk-mitm/files/7037643/decoding.log)

**Comment by dgbkn** [comment] 2021-08-24 08:35
[INFO] Decompiling apk...
I: Using Apktool 2.5.0 on ZEE5mod.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /root/.local/share/apktool/framework/1.apk
I: Regular manifest package...
I: Decoding file-resources...
W: Cant find 9patch chunk in file: "drawable/speech_bubble_right.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "drawable-xxhdpi-v4/speech_bubble_right.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "drawable-hdpi-v4/speech_bubble_right.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "drawable/fb_player_controller_bg.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "drawable-xlarge-v4/speech_bubble_left.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "drawable-xxhdpi-v4/speech_bubble_left.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "drawable-xlarge-v4/message_counter.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "drawable/all_shows_tab_unselected_pressed.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "drawable/popup_top_dark.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "drawable/all_shows_tab_selected_pressed.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "drawable-hdpi-v4/message_counter.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "drawable/speech_bubble_left.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "drawable-mdpi-v4/message_counter.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "drawable-xhdpi-v4/speech_bubble_right.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "drawable/item_focused.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "drawable/bubble_gray_m.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "drawable-hdpi-v4/custom_tab_indicator_divider.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "drawable-large-v4/message_counter.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "drawable/player_controller_bg.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "drawable/popup_top_dark_opaque.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "drawable-xhdpi-v4/custom_tab_indicator_divider.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "drawable/fb_filter_alert_b.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "drawable/switch_thumb.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "drawable/item_pressed.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "drawable/popup_bottom_medium.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "drawable/fb_dropdown_middle_gray.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "drawable/fb_dropdown_middle.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "drawable-xhdpi-v4/feed_incoming_message_bubble.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "drawable/epg_in_app_indication.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "drawable/feed_incoming_message_bubble.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "drawable/dialog_divider_horizontal_light.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "drawable/bubble_blue_b.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "drawable/feed_user_message_bubble.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "drawable-hdpi-v4/speech_bubble_left.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "drawable-hdpi-v4/fb_dropdown_middle.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "drawable/seekbar_progress_bg.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "drawable-xhdpi-v4/feed_user_message_bubble.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "drawable/message_counter.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "drawable/seekbar_bg.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "drawable-mdpi-v4/fb_watch_notification.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "drawable/all_shows_tab_unselected.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "drawable-xhdpi-v4/message_counter.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "drawable-xxhdpi-v4/message_counter.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "drawable/popup_center_bright.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "drawable/grey_layer.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "drawable-mdpi-v4/fb_dropdown_middle.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "drawable/fb_seekbar_progress_bg.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "drawable/navigation_item_pressed.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "drawable-xhdpi-v4/speech_bubble_left.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "drawable/bubble_blue_m.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "drawable/fb_seekbar_bg.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "drawable/switch_thumb_disabled.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "drawable/bubble_gray_b.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "drawable-mdpi-v4/custom_tab_indicator_divider.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "drawable/switch_track_disabled.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "drawable/switch_thumb_pressed.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "drawable-hdpi-v4/fb_watch_notification.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "drawable/all_shows_tab_selected.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "drawable/popup_bottom_medium_opaque.9.png". Renaming it to *.png.
I: Decoding values */* XMLs...
I: Copying raw classes.dex file...
I: Copying raw classes2.dex file...
I: Copying raw classes3.dex file...
I: Copying raw classes4.dex file...
I: Copying raw classes5.dex file...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
I: Copying META-INF/services directory
[INFO] Adding ZEE5mod.apk_1629794024/res/xml/network_security_config.xml...
[INFO] ZEE5mod.apk_1629794024/AndroidManifest.xml has already been modified! No change.
[INFO] Making ZEE5mod.apk_1629794024/AndroidManifest.xml debuggable...
[INFO] Building prepared-ZEE5mod.apk...
I: Using Apktool 2.5.0
I: Copying ZEE5mod.apk_1629794024 classes.dex file...
I: Copying ZEE5mod.apk_1629794024 classes4.dex file...
I: Copying ZEE5mod.apk_1629794024 classes3.dex file...
I: Copying ZEE5mod.apk_1629794024 classes5.dex file...
I: Copying ZEE5mod.apk_1629794024 classes2.dex file...
I: Checking whether resources has changed...
I: Building resources...
W: invalid resource directory name: /content/ZEE5mod.apk_1629794024/res navigation
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/tmp/brut_util_Jar_72475883720478311756550920116607927058.tmp, p, --forced-package-id, 127, --min-sdk-version, 21, --target-sdk-version, 27, --version-code, 203230094, --version-name, 32.92708094.0, --no-version-vectors, -F, /tmp/APKTOOL4332760722027808875.tmp, -e, /tmp/APKTOOL14036355127732836813.tmp, -0, arsc, -I, /root/.local/share/apktool/framework/1.apk, -S, /content/ZEE5mod.apk_1629794024/res, -M, /content/ZEE5mod.apk_1629794024/AndroidManifest.xml]

**Comment by shroudedcode** [comment] 2021-08-24 18:57
The relevant errors can be found in the `encoding-aapt2.failed.log`:

```
W: [...]\decode\res\values\acs.xml:3: error: unknown resource type 'ac'.
W: [...]\decode\res\values\acs.xml: error: file failed to compile.
W: [...]\decode\res\values\public.xml:13800: error: invalid resource type 'ac' in <public>.
W: [...]\decode\res\values\public.xml: error: file failed to compile.
```

These files seem to be invalid in some way and can't be processed by [Apktool](https://github.com/iBotPeaches/Apktool) (which `apk-mitm` is based on). Your only hope is [manually editing them](https://github.com/shroudedcode/apk-mitm/tree/5c3436e1a667a20bc0871fd0a3668c14d23fc363#making-manual-changes) or waiting for an update to Apktool (in case it's a bug which it might not be). Either way, the issue is not specific to `apk-mitm` as it would also occur when [using Apktool in isolation](https://ibotpeaches.github.io/Apktool/documentation/#decoding), so I'm closing this issue.

**Closed by shroudedcode** 2021-08-24 18:57 UTC
