### ISSUE TITLE
apk-mitm downloads apktool although apktool is installed on the machine.

### ISSUE THREAD

**Issue by trieulieuf9** [shroudedcode/apk-mitm#83] opened 2021-11-16 02:29 UTC
Hi, 

I am not sure if it is an issue. When running apk-mitm for the first time, it downloads apktool v2.6.0, although my computer has already installed apktool with this version. this apktool is added to path too.

**Comment by shroudedcode** [comment] 2021-11-16 08:20
Duplicate of #32.

**Closed by shroudedcode** 2021-11-16 08:20 UTC
